async function createGalleryComponent({ name, sites } = { name: 'Gallery Options' }) {
  const type = 'generic';
  const mySites = sites || [location.href.substr(location.href.indexOf('#')).split('/')[2]];
  const postData = {
    name,
    type,
    sites: mySites,
    wysiwyg_render: true,
    struct: {
      '2e017bf5f057c38138fbb95f021923d3': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Slideshow Buttons',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Choose which buttons to show in the slideshow view',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="checkbox" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                name: '2e017bf5f057c38138fbb95f021923d3',
                checked: false,
                index: '0',
                label: 'Auto Play',
                id: '2e017bf5f057c38138fbb95f021923d3',
                value: '"slideShow"',
                required: true,
              },
              {
                itemIndex: '1',
                name: '2e017bf5f057c38138fbb95f021923d3',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'Full Screen',
                id: '2e017bf5f057c38138fbb95f021923d3',
                value: '"fullScreen"',
                required: true,
              },
              {
                itemIndex: '2',
                name: '2e017bf5f057c38138fbb95f021923d3',
                checked: false,
                index: '2',
                className: 'medium',
                label: 'Thumbnails',
                id: '2e017bf5f057c38138fbb95f021923d3',
                value: '"thumbs"',
                required: true,
              },
              {
                itemIndex: '4',
                name: '2e017bf5f057c38138fbb95f021923d3',
                checked: true,
                index: '3',
                className: 'medium',
                label: 'Close',
                id: '2e017bf5f057c38138fbb95f021923d3',
                value: '"close"',
                required: true,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-checkbox-2',
        visualOrder: 6,
        tabIndex: 5,
        label: 'Slideshow Buttons',
        title: 'Checkboxes',
        type: 'checkBox',
        helperText: 'Choose which buttons to show in the slideshow view',
        'formbuilder-element-required-button-text': '',
        content: 'Slideshow Buttons',
        enabled: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            name: '2e017bf5f057c38138fbb95f021923d3',
            checked: false,
            index: '0',
            label: 'Auto Play',
            id: '2e017bf5f057c38138fbb95f021923d3',
            value: '"slideShow"',
            required: true,
          },
          {
            itemIndex: '1',
            name: '2e017bf5f057c38138fbb95f021923d3',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'Full Screen',
            id: '2e017bf5f057c38138fbb95f021923d3',
            value: '"fullScreen"',
            required: true,
          },
          {
            itemIndex: '2',
            name: '2e017bf5f057c38138fbb95f021923d3',
            checked: false,
            index: '2',
            className: 'medium',
            label: 'Thumbnails',
            id: '2e017bf5f057c38138fbb95f021923d3',
            value: '"thumbs"',
            required: true,
          },
          {
            itemIndex: '4',
            name: '2e017bf5f057c38138fbb95f021923d3',
            checked: true,
            index: '3',
            className: 'medium',
            label: 'Close',
            id: '2e017bf5f057c38138fbb95f021923d3',
            value: '"close"',
            required: true,
          },
        ],
        itemIndex: 0,
        name: '2e017bf5f057c38138fbb95f021923d3',
        checkBox: true,
        id: '2e017bf5f057c38138fbb95f021923d3',
        isSelectable: false,
        value: '',
      },
      f0efadfb93f9ef1e1cf2cbfb2f2320f2: {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Initial Slide',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Set the slide to show on load.',
            required: false,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-placeholder-text',
            tabIndex: 3,
            label: 'Placeholder Text',
            value: '3',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              {
                tabIndex: 4,
                label: 'Yes',
                trigger: true,
                value: 'yes',
                checked: false,
                itemIndex: 0,
                name: 'f0efadfb93f9ef1e1cf2cbfb2f2320f2',
                index: '0',
                id: 'f0efadfb93f9ef1e1cf2cbfb2f2320f2',
              },
              {
                checked: true,
                tabIndex: 5,
                label: 'No',
                value: 'no',
                itemIndex: 0,
                name: 'f0efadfb93f9ef1e1cf2cbfb2f2320f2',
                index: '1',
                id: 'f0efadfb93f9ef1e1cf2cbfb2f2320f2',
              },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            input: true,
            updatePreview: true,
            min: 0,
            name: 'formbuilder-element-minLength',
            inputType: 'number',
            className: 'small',
            tabIndex: 7,
            label: 'Minimum Length',
            value: 0,
            helperText: 'Determine the minimum number of characters a user must provide',
            required: false,
          },
          {
            input: true,
            updatePreview: true,
            min: 0,
            name: 'formbuilder-element-maxLength',
            inputType: 'number',
            className: 'small',
            tabIndex: 8,
            label: 'Maximum Length',
            value: 0,
            helperText: 'Determine the maximum number of characters a user can provide',
            required: false,
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            helper: 'Determine if the text field is validated by a regular expression',
            children: 'formbuilder-element-required-responses',
            name: 'formbuilder-element-regex-validation',
            options: [
              {
                itemIndex: 0,
                checked: true,
                tabIndex: 5,
                label: 'Yes',
                trigger: true,
                value: 'yes',
              },
              { itemIndex: 0, checked: false, tabIndex: 6, label: 'No', value: 'no' },
            ],
            label: 'Validate with Regular Expression?',
            required: false,
            radio: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '[\\d]{1,2}',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: 'Please enter a 1-2 digit number.',
            required: true,
          },
        ],
        'formbuilder-element-regex-message': 'Please enter a 1-2 digit number.',
        minLength: 0,
        icon: 'icon-type',
        visualOrder: 12,
        tabIndex: 11,
        label: 'Initial Slide',
        title: 'Short Text',
        type: 'textField',
        helperText: 'Set the slide to show on load.',
        'formbuilder-element-required-button-text': '',
        content: 'Initial Slide',
        enabled: true,
        textField: true,
        'formbuilder-element-regex': '[\\d]{1,2}',
        'placeholder-text': '3',
        itemIndex: 0,
        name: 'f0efadfb93f9ef1e1cf2cbfb2f2320f2',
        id: 'f0efadfb93f9ef1e1cf2cbfb2f2320f2',
        value: '',
        maxLength: 0,
        required: false,
      },
      '8f2d35db90fe37cabd54e9f4bd5b76a8': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Loop Popup Slideshow',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: '',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                checked: true,
                index: '0',
                label: 'Yes',
                value: 'true',
                required: true,
              },
              {
                itemIndex: '1',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'No',
                value: 'false',
                required: true,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-radio-checked',
        visualOrder: 4,
        tabIndex: 3,
        label: 'Loop Popup Slideshow',
        title: 'Radio Buttons',
        type: 'radioButton',
        helperText: '',
        'formbuilder-element-required-button-text': '',
        content: 'Loop Popup Slideshow',
        enabled: true,
        radioButton: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            checked: true,
            index: '0',
            label: 'Yes',
            value: 'true',
            required: true,
          },
          {
            itemIndex: '1',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'No',
            value: 'false',
            required: true,
          },
        ],
        itemIndex: 0,
        name: '8f2d35db90fe37cabd54e9f4bd5b76a8',
        id: '8f2d35db90fe37cabd54e9f4bd5b76a8',
        isSelectable: false,
        value: '',
      },
      '9f086c2af4aa5d1605327f18d7271f9b': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Loop Carousel',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: '',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                checked: true,
                index: '0',
                label: 'Yes',
                value: 'true',
                required: true,
              },
              {
                itemIndex: '1',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'No',
                value: 'false',
                required: true,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-radio-checked',
        visualOrder: 11,
        tabIndex: 10,
        label: 'Loop Carousel',
        title: 'Radio Buttons',
        type: 'radioButton',
        helperText: '',
        'formbuilder-element-required-button-text': '',
        content: 'Loop Carousel',
        enabled: true,
        radioButton: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            checked: true,
            index: '0',
            label: 'Yes',
            value: 'true',
            required: true,
          },
          {
            itemIndex: '1',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'No',
            value: 'false',
            required: true,
          },
        ],
        itemIndex: 0,
        name: '9f086c2af4aa5d1605327f18d7271f9b',
        id: '9f086c2af4aa5d1605327f18d7271f9b',
        isSelectable: false,
        value: '',
      },
      '102d4c9baf6d8fff5168c868bf31a744': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Slides to Scroll',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Set the number of slides to scroll at a time',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                checked: true,
                index: '0',
                label: '1',
                value: '1',
                required: true,
                selected: true,
              },
              {
                itemIndex: '1',
                checked: false,
                index: '1',
                className: 'medium',
                label: '2',
                value: '2',
                required: true,
                selected: false,
              },
              {
                itemIndex: '2',
                checked: false,
                index: '2',
                className: 'medium',
                label: '3',
                value: '3',
                required: true,
                selected: false,
              },
              {
                itemIndex: '3',
                checked: false,
                index: '3',
                className: 'medium',
                label: '4',
                value: '4',
                required: true,
                selected: false,
              },
              {
                itemIndex: '4',
                checked: false,
                index: '4',
                className: 'medium',
                label: '5',
                value: '5',
                required: true,
                selected: false,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        dropDown: true,
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-menu-6',
        visualOrder: 14,
        tabIndex: 13,
        label: 'Slides to Scroll',
        title: 'Drop-Down',
        type: 'dropDown',
        helperText: 'Set the number of slides to scroll at a time',
        'formbuilder-element-required-button-text': '',
        content: 'Slides to Scroll',
        enabled: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            checked: true,
            index: '0',
            label: '1',
            value: '1',
            required: true,
            selected: true,
          },
          {
            itemIndex: '1',
            checked: false,
            index: '1',
            className: 'medium',
            label: '2',
            value: '2',
            required: true,
            selected: false,
          },
          {
            itemIndex: '2',
            checked: false,
            index: '2',
            className: 'medium',
            label: '3',
            value: '3',
            required: true,
            selected: false,
          },
          {
            itemIndex: '3',
            checked: false,
            index: '3',
            className: 'medium',
            label: '4',
            value: '4',
            required: true,
            selected: false,
          },
          {
            itemIndex: '4',
            checked: false,
            index: '4',
            className: 'medium',
            label: '5',
            value: '5',
            required: true,
            selected: false,
          },
        ],
        itemIndex: 0,
        name: '102d4c9baf6d8fff5168c868bf31a744',
        id: '102d4c9baf6d8fff5168c868bf31a744',
        isSelectable: true,
        value: '',
      },
      '4879988da73a3b13d5013a777e0d5027': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Autoplay',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: '',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                name: '4879988da73a3b13d5013a777e0d5027',
                checked: true,
                index: '0',
                label: 'Yes',
                id: '4879988da73a3b13d5013a777e0d5027',
                value: 'true',
                required: true,
              },
              {
                itemIndex: '1',
                name: '4879988da73a3b13d5013a777e0d5027',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'No',
                id: '4879988da73a3b13d5013a777e0d5027',
                value: 'false',
                required: true,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-radio-checked',
        visualOrder: 8,
        tabIndex: 7,
        label: 'Autoplay',
        title: 'Radio Buttons',
        type: 'radioButton',
        helperText: '',
        'formbuilder-element-required-button-text': '',
        content: 'Autoplay',
        enabled: true,
        radioButton: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            name: '4879988da73a3b13d5013a777e0d5027',
            checked: true,
            index: '0',
            label: 'Yes',
            id: '4879988da73a3b13d5013a777e0d5027',
            value: 'true',
            required: true,
          },
          {
            itemIndex: '1',
            name: '4879988da73a3b13d5013a777e0d5027',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'No',
            id: '4879988da73a3b13d5013a777e0d5027',
            value: 'false',
            required: true,
          },
        ],
        itemIndex: 0,
        name: '4879988da73a3b13d5013a777e0d5027',
        id: '4879988da73a3b13d5013a777e0d5027',
        isSelectable: false,
        value: '',
      },
      '2a54742a6b9f747ee33f4ec8b65fd227': {
        hasAdvanced: false,
        settings: [
          {
            markup:
              '<div class="insttext_editor {{wysiwygid}}" data-wysiwygid="{{wysiwygid}}"></div>',
            name: 'formbuilder-element-wysiwyg',
            html: true,
            label: '',
            value: '<h4>Popup Options</h4>',
            required: true,
          },
        ],
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            helper: 'Determine if the text field is validated by a regular expression',
            children: 'formbuilder-element-required-responses',
            name: 'formbuilder-element-regex-validation',
            options: [
              { tabIndex: 5, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 6, label: 'No', value: 'no' },
            ],
            label: 'Validate with Regular Expression?',
            required: false,
            radio: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-quote',
        visualOrder: 3,
        instructionalText: true,
        tabIndex: 2,
        label: '<h4>Popup Options</h4>',
        title: 'Instructional Text',
        type: 'instructionalText',
        'formbuilder-element-required-button-text': '',
        htmlPreview: true,
        content: '<h4>Popup Options</h4>',
        enabled: true,
        wysiwygEditor: true,
        'formbuilder-element-regex': '',
        name: '2a54742a6b9f747ee33f4ec8b65fd227',
        itemIndex: 0,
        id: '2a54742a6b9f747ee33f4ec8b65fd227',
        value: '',
      },
      f2f4219d981b3106a721c4d63fe57965: {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Slideshow Arrows',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Display arrows in the slideshow view',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                checked: true,
                index: '0',
                label: 'Yes',
                value: 'true',
                required: true,
              },
              {
                itemIndex: '1',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'No',
                value: 'false',
                required: true,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-radio-checked',
        visualOrder: 5,
        tabIndex: 4,
        label: 'Slideshow Arrows',
        title: 'Radio Buttons',
        type: 'radioButton',
        helperText: 'Display arrows in the slideshow view',
        'formbuilder-element-required-button-text': '',
        content: 'Slideshow Arrows',
        enabled: true,
        radioButton: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            checked: true,
            index: '0',
            label: 'Yes',
            value: 'true',
            required: true,
          },
          {
            itemIndex: '1',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'No',
            value: 'false',
            required: true,
          },
        ],
        itemIndex: 0,
        name: 'f2f4219d981b3106a721c4d63fe57965',
        id: 'f2f4219d981b3106a721c4d63fe57965',
        isSelectable: false,
        value: '',
      },
      '6fcac3f070a7b02020eaf558f34e9473': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Carousel Arrows',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Display navigation arrows for the carousel',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                checked: true,
                index: '0',
                label: 'Yes',
                value: 'true',
                required: true,
              },
              {
                itemIndex: '1',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'No',
                value: 'false',
                required: true,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-radio-checked',
        visualOrder: 10,
        tabIndex: 9,
        label: 'Carousel Arrows',
        title: 'Radio Buttons',
        type: 'radioButton',
        helperText: 'Display navigation arrows for the carousel',
        'formbuilder-element-required-button-text': '',
        content: 'Carousel Arrows',
        enabled: true,
        radioButton: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            checked: true,
            index: '0',
            label: 'Yes',
            value: 'true',
            required: true,
          },
          {
            itemIndex: '1',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'No',
            value: 'false',
            required: true,
          },
        ],
        itemIndex: 0,
        name: '6fcac3f070a7b02020eaf558f34e9473',
        id: '6fcac3f070a7b02020eaf558f34e9473',
        isSelectable: false,
        value: '',
      },
      '9aa998329f35d96122f86beba623e740': {
        hasAdvanced: false,
        settings: [
          {
            markup:
              '<div class="insttext_editor {{wysiwygid}}" data-wysiwygid="{{wysiwygid}}"></div>',
            name: 'formbuilder-element-wysiwyg',
            html: true,
            label: '',
            value: '<h4>Carousel Options</h4>',
            required: true,
          },
        ],
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            helper: 'Determine if the text field is validated by a regular expression',
            children: 'formbuilder-element-required-responses',
            name: 'formbuilder-element-regex-validation',
            options: [
              { tabIndex: 5, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 6, label: 'No', value: 'no' },
            ],
            label: 'Validate with Regular Expression?',
            required: false,
            radio: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-quote',
        visualOrder: 7,
        instructionalText: true,
        tabIndex: 6,
        label: '<h4>Carousel Options</h4>',
        title: 'Instructional Text',
        type: 'instructionalText',
        'formbuilder-element-required-button-text': '',
        htmlPreview: true,
        content: '<h4>Carousel Options</h4>',
        enabled: true,
        wysiwygEditor: true,
        'formbuilder-element-regex': '',
        name: '9aa998329f35d96122f86beba623e740',
        itemIndex: 0,
        id: '9aa998329f35d96122f86beba623e740',
        value: '',
      },
      '783e361ef7d3f3248cf4bec6009a38f0': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Gallery Asset',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Choose a gallery asset',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              {
                itemIndex: 0,
                checked: true,
                tabIndex: 4,
                label: 'Yes',
                trigger: true,
                value: 'yes',
              },
              { itemIndex: 0, checked: false, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
        ],
        isRequired: true,
        'formbuilder-element-available-assets': '',
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            selectSingle: true,
            name: 'formbuilder-element-filechooser-avail-file-types',
            options: [
              { checked: true, label: 'Web Content', value: 'generic' },
              { label: 'Plain Text', value: 'text' },
              { label: 'Source Code', value: 'code' },
              { label: 'Image Gallery', value: 'gallery', selected: true },
              { labeltom: 'Form', value: 'form' },
            ],
            label: 'Available File Types',
            value: 'gallery',
          },
          {
            name: 'formbuilder-element-available-assets',
            tagChooser: true,
            label: 'Available Assets by Tag',
            value: '',
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-loop',
        visualOrder: 1,
        tabIndex: 0,
        label: 'Gallery Asset',
        title: 'Asset Chooser',
        type: 'assetChooser',
        helperText: 'Choose a gallery asset',
        'formbuilder-element-required-button-text': '',
        content: 'Gallery Asset',
        enabled: true,
        assetChooser: true,
        'formbuilder-element-regex': '',
        itemIndex: 0,
        name: '783e361ef7d3f3248cf4bec6009a38f0',
        id: '783e361ef7d3f3248cf4bec6009a38f0',
        value: '',
      },
      '89f1a686d87607d77717ecc9ea396cc1': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Gallery Output Type',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Choose a gallery type',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              {
                itemIndex: 0,
                checked: true,
                tabIndex: 4,
                label: 'Yes',
                trigger: true,
                value: 'yes',
              },
              { itemIndex: 0, checked: false, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                name: '89f1a686d87607d77717ecc9ea396cc1',
                checked: false,
                index: '0',
                label: 'Popup Slideshow Gallery',
                id: '89f1a686d87607d77717ecc9ea396cc1',
                value: 'fancybox',
                required: true,
                selected: true,
              },
              {
                itemIndex: '1',
                name: '89f1a686d87607d77717ecc9ea396cc1',
                checked: false,
                index: '1',
                className: 'medium',
                label: 'Carousel Gallery',
                id: '89f1a686d87607d77717ecc9ea396cc1',
                value: 'slick',
                required: true,
                selected: false,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        dropDown: true,
        isRequired: true,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-menu-6',
        visualOrder: 2,
        tabIndex: 1,
        label: 'Gallery Output Type',
        title: 'Drop-Down',
        type: 'dropDown',
        helperText: 'Choose a gallery type',
        'formbuilder-element-required-button-text': '',
        content: 'Gallery Output Type',
        enabled: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            name: '89f1a686d87607d77717ecc9ea396cc1',
            checked: false,
            index: '0',
            label: 'Popup Slideshow Gallery',
            id: '89f1a686d87607d77717ecc9ea396cc1',
            value: 'fancybox',
            required: true,
            selected: true,
          },
          {
            itemIndex: '1',
            name: '89f1a686d87607d77717ecc9ea396cc1',
            checked: false,
            index: '1',
            className: 'medium',
            label: 'Carousel Gallery',
            id: '89f1a686d87607d77717ecc9ea396cc1',
            value: 'slick',
            required: true,
            selected: false,
          },
        ],
        itemIndex: 0,
        name: '89f1a686d87607d77717ecc9ea396cc1',
        id: '89f1a686d87607d77717ecc9ea396cc1',
        isSelectable: true,
        value: '',
      },
      '9580abd832651dd388bce7b09419c68a': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Autoplay Speed',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Set the duration a slide is shown in milliseconds.',
            required: false,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-placeholder-text',
            tabIndex: 3,
            label: 'Placeholder Text',
            value: '4000',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            input: true,
            updatePreview: true,
            min: 0,
            name: 'formbuilder-element-minLength',
            inputType: 'number',
            className: 'small',
            tabIndex: 7,
            label: 'Minimum Length',
            value: '4',
            helperText: 'Determine the minimum number of characters a user must provide',
            required: false,
          },
          {
            input: true,
            updatePreview: true,
            min: 0,
            name: 'formbuilder-element-maxLength',
            inputType: 'number',
            className: 'small',
            tabIndex: 8,
            label: 'Maximum Length',
            value: '5',
            helperText: 'Determine the maximum number of characters a user can provide',
            required: false,
          },
        ],
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            helper: 'Determine if the text field is validated by a regular expression',
            children: 'formbuilder-element-required-responses',
            name: 'formbuilder-element-regex-validation',
            options: [
              {
                itemIndex: 0,
                checked: true,
                tabIndex: 5,
                label: 'Yes',
                trigger: true,
                value: 'yes',
              },
              { itemIndex: 0, checked: false, tabIndex: 6, label: 'No', value: 'no' },
            ],
            label: 'Validate with Regular Expression?',
            required: false,
            radio: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '[\\d]{4,5}',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: 'This value must be a 4-5 digit number.',
            required: true,
          },
        ],
        'formbuilder-element-regex-message': 'This value must be a 3-5 digit number.',
        minLength: '4',
        icon: 'icon-type',
        visualOrder: 9,
        tabIndex: 8,
        label: 'Autoplay Speed',
        title: 'Short Text',
        type: 'textField',
        helperText: 'Set the duration a slide is shown in milliseconds.',
        'formbuilder-element-required-button-text': '',
        content: 'Autoplay Speed',
        enabled: true,
        textField: true,
        'formbuilder-element-regex': '[\\d]{3,5}',
        'placeholder-text': '4000',
        itemIndex: 0,
        name: '9580abd832651dd388bce7b09419c68a',
        id: '9580abd832651dd388bce7b09419c68a',
        value: '',
        maxLength: '5',
      },
      '4015aa8231d8979fbf3295055b529083': {
        hasAdvanced: true,
        settings: [
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-label',
            tabIndex: 1,
            label: 'Label',
            value: 'Slides to Show',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            name: 'formbuilder-element-helperText',
            tabIndex: 2,
            label: 'Helper Text',
            value: 'Set the number of slides to show at a time',
            required: false,
          },
          {
            children: 'formbuilder-element-required-error-msg',
            name: 'formbuilder-element-required-field',
            options: [
              { tabIndex: 4, label: 'Yes', trigger: true, value: 'yes' },
              { checked: true, tabIndex: 5, label: 'No', value: 'no' },
            ],
            label: 'Required Field?',
            required: true,
            radio: true,
          },
          {
            isDynamic: true,
            markup:
              '\n\t\t<div class="controls formbuilder-checkbox-item" data-index="0">\n\t\t\t<i class="icon-menu-2"></i>\n\t\t\t<input type="radio" class="" data-index="0" data-name="formbuilder-element-checkbox-item" />\n\t\t\t<input type="text" value="" data-index="0" class="formbuilder-element-checkbox-item0 medium" data-name="formbuilder-element-checkbox-item" data-custom="prop" >\n\t\t\t<i class="icon-cancel-2 " data-index="0"></i>\n\t\t\t<!--<p class="formbuilder-element-checkbox-item help-block"></p>-->\n\t\t</div>\n',
            name: 'formbuilder-element-checkbox-item',
            options: [
              {
                itemIndex: '0',
                checked: true,
                index: '0',
                label: '1',
                value: '1',
                required: true,
                selected: true,
              },
              {
                itemIndex: '1',
                checked: false,
                index: '1',
                className: 'medium',
                label: '2',
                value: '2',
                required: true,
                selected: false,
              },
              {
                itemIndex: '2',
                checked: false,
                index: '2',
                className: 'medium',
                label: '3',
                value: '3',
                required: true,
                selected: false,
              },
              {
                itemIndex: '3',
                checked: false,
                index: '3',
                className: 'medium',
                label: '4',
                value: '4',
                required: true,
                selected: false,
              },
              {
                itemIndex: '4',
                checked: false,
                index: '4',
                className: 'medium',
                label: '5',
                value: '5',
                required: true,
                selected: false,
              },
            ],
            html: true,
            label: 'Items',
            required: true,
          },
          {
            button: true,
            customAttr: 'formbuilder-element-checkbox-item',
            name: 'formbuilder-element-checkbox-button',
          },
        ],
        dropDown: true,
        isRequired: false,
        advanced: [
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-additional-responses',
            name: 'formbuilder-element-required-button-text',
            tabIndex: 4,
            label: 'Additional Response Button Text',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex',
            className: 'medium',
            tabIndex: 3,
            label: 'Regex',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            input: true,
            updatePreview: true,
            parent: 'formbuilder-element-regex-validation',
            name: 'formbuilder-element-regex-message',
            tabIndex: 4,
            label: 'Error Message',
            trigger: 'yes',
            value: '',
            required: true,
          },
          {
            markup:
              '\n<div class="control-group formbuilder-element-labl-value-map" data-id="">\n\t\t\t<label class="control-label display-label-map medium"><strong>Display Name</strong></label>\n\t\t\t<label class="control-label display-label-map medium"><strong>Value</strong></label>\n\t\t\t<div class="controls display-value-map">\n\n\t\t\t</div>\n</div>\n',
            name: 'formbuilder-element-value-map',
            html: true,
          },
        ],
        'formbuilder-element-regex-message': '',
        icon: 'icon-menu-6',
        visualOrder: 13,
        tabIndex: 12,
        label: 'Slides to Show',
        title: 'Drop-Down',
        type: 'dropDown',
        helperText: 'Set the number of slides to show at a time',
        'formbuilder-element-required-button-text': '',
        content: 'Slides to Show',
        enabled: true,
        'formbuilder-element-regex': '',
        options: [
          {
            itemIndex: '0',
            checked: true,
            index: '0',
            label: '1',
            value: '1',
            required: true,
            selected: true,
          },
          {
            itemIndex: '1',
            checked: false,
            index: '1',
            className: 'medium',
            label: '2',
            value: '2',
            required: true,
            selected: false,
          },
          {
            itemIndex: '2',
            checked: false,
            index: '2',
            className: 'medium',
            label: '3',
            value: '3',
            required: true,
            selected: false,
          },
          {
            itemIndex: '3',
            checked: false,
            index: '3',
            className: 'medium',
            label: '4',
            value: '4',
            required: true,
            selected: false,
          },
          {
            itemIndex: '4',
            checked: false,
            index: '4',
            className: 'medium',
            label: '5',
            value: '5',
            required: true,
            selected: false,
          },
        ],
        itemIndex: 0,
        name: '4015aa8231d8979fbf3295055b529083',
        id: '4015aa8231d8979fbf3295055b529083',
        isSelectable: true,
        value: '',
      },
    },
    source:
      '<ouc:component name="gallery-options">\n\t<table class="ou-" data-snippet="ou-component-gallery">\n\t\t<caption>Gallery with Options</caption>\n\t\t<tbody>\n\t\t\t<tr>\n\t\t\t\t<th>Gallery Asset</th>\n\t\t\t\t<td data-variable="gallery-asset">[[783e361ef7d3f3248cf4bec6009a38f0]]</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th>Gallery Type</th>\n\t\t\t\t<td data-variable="gallery-type">[[89f1a686d87607d77717ecc9ea396cc1]]</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th>Popup Options</th>\n\t\t\t\t<td data-type="fancybox">\n\t\t\t\t\t<dl>\n\t\t\t\t\t\t<dt>Loop Popup Slideshow</dt>\n\t\t\t\t\t\t<dd data-key="loop">[[8f2d35db90fe37cabd54e9f4bd5b76a8]]</dd>\n\t\t\t\t\t\t<dt>Display Slideshow Arrows</dt>\n\t\t\t\t\t\t<dd data-key="arrows">[[f2f4219d981b3106a721c4d63fe57965]]</dd>\n\t\t\t\t\t\t<dt>Enabled Slideshow Buttons</dt>\n\t\t\t\t\t\t<dd data-key="buttons">[[[2e017bf5f057c38138fbb95f021923d3]]]</dd>\n\t\t\t\t\t</dl>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<th>Carousel Options</th>\n\t\t\t\t<td data-type="slick">\n\t\t\t\t\t<dl>\n\t\t\t\t\t\t<dt>Autoplay</dt>\n\t\t\t\t\t\t<dd data-key="autoplay">[[4879988da73a3b13d5013a777e0d5027]]</dd>\n\t\t\t\t\t\t<dt>Autoplay Speed</dt>\n\t\t\t\t\t\t<dd data-key="autoplaySpeed">[[9580abd832651dd388bce7b09419c68a]]</dd>\n\t\t\t\t\t\t<dt>Display Carousel Arrows</dt>\n\t\t\t\t\t\t<dd data-key="arrows">[[6fcac3f070a7b02020eaf558f34e9473]]</dd>\n\t\t\t\t\t\t<dt># of Slides Displayed at a Time</dt>\n\t\t\t\t\t\t<dd data-key="slidesToShow">[[4015aa8231d8979fbf3295055b529083]]</dd>\n\t\t\t\t\t\t<dt># of Slides Scrolled at a Time</dt>\n\t\t\t\t\t\t<dd data-key="slidesToScroll">[[102d4c9baf6d8fff5168c868bf31a744]]</dd>\n\t\t\t\t\t\t<dt>Loop Slides</dt>\n\t\t\t\t\t\t<dd data-key="infinite">[[9f086c2af4aa5d1605327f18d7271f9b]]</dd>\n\t\t\t\t\t\t<dt>Start at Slide #</dt>\n\t\t\t\t\t\t<dd data-key="initialSlide">[[f0efadfb93f9ef1e1cf2cbfb2f2320f2]]</dd>\n\t\t\t\t\t</dl>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</tbody>\n\t</table>\n</ouc:component>',
  };

  const createComponent = await fetch('/rs/components', {
    method: 'post',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(postData),
  });

  if (createComponent.status === 201) {
    console.log('Component created. Launching component now.');
    const launchComponent = await fetch('/rs/components/launch', {
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: `/${name}`, type, message: 'Initial launch.' }),
    });
    if (launchComponent.status === 202) {
      console.log('Component launched!');
    } else {
      console.log('Something happened during launch.', launchComponent);
    }
  } else if (createComponent.status === 400) {
    console.log({
      status: createComponent.status,
      message: 'This usually means there was a name conflict',
    });
  }
}

createGalleryComponent();
